### ISSUE TITLE
Armor Modules seem to work without steam/rf

### ISSUE THREAD

**Issue by decebaldecebal** [BrassGoggledCoders/SteamCraft2#293] opened 2015-07-09 11:22 UTC
I tested the Goggles and the Jetpack, both work without having a steam canister or electric jar in inventory...
Also the Jetpack seems to use steam from a canister when there is one(while falling).

I'l let you handle this since I do not know how the whole system works :)

**Comment by warlordjones** [comment] 2015-07-09 13:36
Lol, I expected something like this. The whole system is due a bit of an overhaul, but its currently not a priority :P Watch this space!

**Comment by warlordjones** [comment] 2015-08-26 11:19
Technically a dupe of #302 now

**Closed by warlordjones** 2015-08-26 11:19 UTC
Labels: bug
