### ISSUE TITLE
TileBaseBoiler NPE

### ISSUE THREAD

**Issue by SkySom** [BrassGoggledCoders/SteamCraft2#362] opened 2016-03-07 21:27 UTC
Pulling this from the CF comments so it doesn't get missed:
https://gist.github.com/SkySom/163f3b45400d2069f08c

**Comment by SkySom** [comment] 2016-03-07 21:28
Just be careful if you push a build @warlordjones considering you'd have to put out a new Boilerplate, I'd have to put out a new MoarCarts, so give me a heads up if you do a new build

**Comment by FreneticScribbler** [comment] 2016-03-07 22:03
Oke. Not looking likely atm, I'm hella busy with school.

**Comment by SkySom** [comment] 2016-03-07 22:05
Alright. Keep on keepin'

**Comment by FreneticScribbler** [comment] 2016-06-12 18:21
Closing for now as I cannot reproduce this.

**Closed as completed by FreneticScribbler** 2016-06-12 18:21 UTC
Labels: bug, critical, more info needed
