### ISSUE TITLE
[minor] wire transfers power to battery but doesn't appear to "connect" to top. (bounding box?)

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#272] opened 2015-06-24 12:38 UTC
![2015-06-24_05 33 28](https://cloud.githubusercontent.com/assets/11265900/8329971/e6a61534-1a32-11e5-87ce-1fa818ecff26.png)

**Comment by decebaldecebal** [comment] 2015-06-24 12:55
The Battery model is smaller than a full block, and the wires only render in their block space.The battery model could be made bigger so it is a full block tall.

**Comment by TheQuadShot** [comment] 2015-06-24 12:59
Maybe this should be tagged as an enhancement?

**Comment by warlordjones** [comment] 2015-06-24 13:09
Right, yeah, I need to redo the battery bank model

**Comment by warlordjones** [comment] 2015-06-28 12:20
Same thing is happening with the copper tank. Hmm.

**Comment by warlordjones** [comment] 2015-06-28 12:23
Ah, this is a dupe of #226 actually. Closing newer as usual.

**Closed by warlordjones** 2015-06-28 12:23 UTC
Labels: enhancement, minor
