### ISSUE TITLE
Lightning rod crash, corrupt save

### ISSUE THREAD

**Issue by TekHed** [BrassGoggledCoders/SteamCraft2#173] opened 2015-01-10 01:12 UTC
I mentioned this on minecraftforum.net but here is a real post. 

I had a lightning rod atop a post, not connected to anything just to try out and see how often it hit. On my next trip to the Nether I started lagging and crashing. I was able to get back in game a few times but crashing again within seconds, eventually the save game corrupted completely and had to revert to previous backup.

Crash log blamed ticking entity: lightning rod, weather said raining if that helps. I can provide the actual full cash log(s) if you want.

**Comment by warlordjones** [comment] 2015-01-10 11:17
I think I know the issue, I'll test this out later today

**Comment by warlordjones** [comment] 2015-01-10 13:20
Hmm, I can't seem to reproduce. A full crash log would therefore be useful  (I may already have accidentally fixed the issue)

**Comment by warlordjones** [comment] 2015-01-10 16:07
I *think* I already fixed this, I can't reproduce this issue. Closing for now, I'll reopen if I'm able to reproduce it.

**Closed by warlordjones** 2015-01-10 16:07 UTC
Labels: aronafail, bug, critical

**Comment by MrIbby** [comment] 2015-01-10 20:28
Now that's a bad reason :P

**Comment by warlordjones** [comment] 2015-01-10 20:30
True, true, but I want to get it off the issue tracker :P

**Comment by MrIbby** [comment] 2015-01-11 01:47
Probably should release a new version sometime soon. A lot of people are coming back with old bugs.

**Comment by warlordjones** [comment] 2015-01-11 09:00
Planning to.
