### ISSUE TITLE
Crash with Fastcraft

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#262] opened 2015-06-23 18:47 UTC
I was trying this mod with fastcraft installed, and this happened. It says steamcraft2 a lot, so I think it might be related. I was trying to create a world.

http://pastebin.com/N1gFQ6Wy

**Comment by warlordjones** [comment] 2015-06-24 07:51
Looks like incompat with the deeps dimension, I'll take a look

**Comment by warlordjones** [comment] 2015-06-28 11:40
Hrm, I believe this is a duplicate of #282 - it seems to occur with and without fastcraft. As such, closing this for now.

**Closed by warlordjones** 2015-06-28 11:40 UTC
Labels: ???, bug, critical
